spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/commerce_db
    username: ockddak
    password: ockddak123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: U2VjcmV0S2V5Rm9yRWNvbW1lcmNlUGxhdGZvcm1TZXJ2aWNlV2l0aEpXVAo=
  access-token-expiration-ms: 1800000